Display: False
attn_drop: 0.3
batch_size: 128
cv_folds: 5
data_dir: data/Lung_Cancer_Matrix
drop_neg: 0.3
drop_rate: 0.3
heads: 4
hidden_channels: 24
pos_lambda: 0.1
neg_lambda: 0.1
learnable_factor: True
lr: 0.002
load_data: True
log_dir: log
loss: MMD
model: Multi_GTN
num_epochs: 500
num_neighbors: [40, 10]
overlap: False
pooling: max
PPI: ['CPDB', 'IRef', 'Multinet', 'PCNet', 'STRING']
pre_drop_rate: 0
project: MPIT
random_seed: 42
repeat: 1
residual: 1.
sample_rate: 1.0
stable: True
start_epoch: 100
out_dir: outs
wandb: True
weight_decay: 0.005